### ISSUE TITLE
在 define 代码块里使用 require 异步回调时 require([deps], function(dep) {})，会造成 release 后的 module ID 位置错误。

### ISSUE THREAD

**Issue by aftdotleo** [fex-team/fis-postprocessor-amd#11]
Hi 各位好，

问题：情况如标题所述。
环境：fisp + fis-postprocessor-amd
代码：

```javascript
// Module: chart
define(function (require) {
    var _ = require('underscore');

    /* do something */

    return function () {
        // 异步
        require(['echarts', 'echarts/chart/line', 'echarts/chart/bar'], function (ec) {
            /* do something */
        });
});
```

***如果在异步 require 的 deps 里声明超过两个 2 依赖时，release 之后这个模块的 ID 就会错位。***

```javascript
define(['require', 'common:widget/lib/underscore/underscore', 'tally:widget/lib/test/profitLine', 'tally:widget/lib/test/profitDaily', 'tally:widget/lib/tool/format', 'tally:widget/lib/echartsTheme'],***'tally:widget/chart/chart',*** function (require) {
...
});
```

另外，
如果在异步 require 的 deps 里声明***不超过两个 2 依赖时（1个或2个）***，release 之后这个模块的 ID 就是正常的。

**Comment by 2betop** [comment]
我来看看怎么回事

**Comment by 2betop** [comment]
没出现你说的这个问题，能否提供一个完整的测试包？

**Comment by aftdotleo** [comment]
@2betop 

完整测试包：http://pan.baidu.com/s/1o6xBOIu

谢谢！

**Comment by aftdotleo** [comment]
缩小了下范围，代码：
`
define(function (require) {
    var $ = jQuery;
    var _ = require('underscore');

    function Chart(option) {
        option = option || {};
        this.ec = option.ec;

        // 好像问题在这里，任意注释下面一行代码，module id 都会正常。
        this.raw = require('lib/test/profitLine').data;
        this.raw2 = require('lib/test/profitDaily').data;
        this.formatter = require('lib/tool/format');
        this.theme = require('lib/echartsTheme');
    }

    // init
    return function () {
        require(['echarts', 'echarts/chart/line', 'echarts/chart/bar'], function (ec) {
            console.log(ec);
        });
    };
});
`

**Comment by 2betop** [comment]
好的，我先看看

**Comment by 2betop** [comment]
重现了，我来看看怎么回事。

**Comment by 2betop** [comment]
已解决

**Comment by 2betop** [comment]
多个 replace 的位置点一样，需要考虑优先级，请更新版本。

**Comment by aftdotleo** [comment]
Hi @2betop 

我已经升级到 0.2.15，但是在 release 后问题依旧存在。请问还需要修改什么地方吗？

**Comment by 2betop** [comment]
你是不是忘记 -c 了？

**Comment by aftdotleo** [comment]
不好意思，是忘记加上 -c 了。

赞效率！谢谢！
