### ISSUE TITLE
noOnymousModule建议写在文档里，fisp下挺重要

### ISSUE THREAD

**Issue by zgp626** [fex-team/fis-postprocessor-amd#12]
![image](https://cloud.githubusercontent.com/assets/549974/5952770/37c44306-a7b9-11e4-90f1-d471edd82658.png)

**Comment by 2betop** [comment]
不应该是 true 吗？

**Comment by zgp626** [comment]
没有啊，默认是false
https://github.com/fex-team/fis-postprocessor-amd/blob/master/index.js#L225

**Comment by 2betop** [comment]
我的意思是，如果想让跨模块调用的时候不出错，应该设置成 true

其实呢，大家都别写署名模块就都没事了。

**Comment by zgp626** [comment]
是，自己的js都没写署名，但是用requirejs的目的就是为了用第三方类库方便，这些类库普遍自己署名了。

**Comment by 2betop** [comment]
好吧，了解了。

另外推荐个东西。https://github.com/fis-components

**Comment by 2betop** [comment]
发错了，在这 https://github.com/fis-components/components

**Comment by zgp626** [comment]
对，我没说明白，我是说这个api在文档和各个demo里都没有，我是看了源码才知道有这个东西的……

**Comment by fouber** [comment]
@2betop 

这个属性为什么不是 ``anonymous`` ，而是 ``noOnymous`` ？

**Comment by xiangshouding** [comment]
应该当初词穷了吧。

**Comment by 2betop** [comment]
不是词穷，本想 Allow Onymous
觉得长就用no
了

**Comment by xiangshouding** [comment]
了解了
