### ISSUE TITLE
如何加载非AMD或者CMD的模块

### ISSUE THREAD

**Issue by fengsx** [fex-team/fis-postprocessor-amd#9]
如果一个js比如humanize.js不符合模块化规范，但是想作为一个模块引入。用这个插件生成resourcemap会出现路径解析错误，并导致程序不可用。这是为什么？
有没有那种类似将cmd解析为amd工具，来将这种非模块化代码段在外层自动套上define呢？

**Comment by 2betop** [comment]
在 fis 中，被 roadmap.path 配置命中 isMod 的 js 文件都会自动 cmd => amd

**Comment by fengsx** [comment]
嗯。。。我说的是，如果这个模块是个js功能块，没有define过，就会报错。如下：



静态文件是 a/b.html
js是     c/d.js
然后d.js内容是console.log('ddddd')
用这个插件，无论在fis-conf.js中怎么写，都会报错的。
解析不到这个文件路径的。
